### ISSUE TITLE
Project License

### ISSUE THREAD

**Issue by tonyo** [Meoo/premake-androidmk#2]
Thanks for the project!
We'd really like to use it for one of our build pipelines at [Sentry](https://github.com/getsentry/).
However, the problem is that the repository doesn't include the license at the moment.
Quoting [GitHub Licensing Guide](https://help.github.com/en/articles/licensing-a-repository#what-happens-if-i-dont-choose-a-license):

> You're under no obligation to choose a license. However, without a license, the default copyright laws apply, meaning that you retain all rights to your source code and no one may reproduce, distribute, or create derivative works from your work.

Could you please add a license?

**Comment by Meoo** [comment]
There you go, licensed under the BSD 3-clause license

**Comment by tonyo** [comment]
Thanks a lot 👍
